# Generated by Django 4.1.4 on 2022-12-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IELTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='{{ i.image.url }}')),
                ('candidate_id', models.CharField(max_length=9)),
                ('date', models.DateField()),
                ('family_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(help_text='Year | Month | Day')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
                ('region_address', models.CharField(max_length=200)),
                ('nationally', models.CharField(max_length=100)),
                ('first_language', models.CharField(max_length=100)),
                ('grammar', models.FloatField(blank=True, null=True)),
                ('pronunciation', models.FloatField(blank=True, null=True)),
                ('fluency', models.FloatField(blank=True, null=True)),
                ('coherence', models.FloatField(blank=True, null=True)),
                ('admission_comments', models.TextField(blank=True, null=True)),
                ('test_number', models.IntegerField()),
                ('candidate_number', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'IELTS',
                'verbose_name_plural': 'IELTS',
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Pupil name....', max_length=400)),
                ('date', models.DateField(blank=True, help_text='Date | Month | Year', null=True)),
                ('email_address', models.CharField(help_text='Enter email address ...', max_length=200, null=True)),
                ('phone_number', models.IntegerField()),
                ('passport_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment', models.BooleanField(help_text='if paid, click the button')),
                ('one_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
